export { default as SvgEmptyBox } from './SvgEmptyBox'
export { default as SvgEmptyMsg } from './SvgEmptyMsg'
export { default as SvgInmuebleIcon } from './SvgInmuebleIcon'
export { default as SvgAutosIcon } from './SvgAutosIcon'
export { default as SvgMascotasIcon } from './SvgMascotasIcon'
export { default as SvgNiñosIcon } from './SvgNiñosIcon'
export { default as SvgEmpleosIcon } from './SvgEmpleosIcon'
